default['jdk']['user_id'] = 'rusa'
default['jdk']['group'] = 'sgsup'
default['jdk']['root'] = '/apps/jdk-bin'
default['jdk']['conf_root'] = '/apps/jdk-apps'
default['jdk']['rpm_file'] = '/apps/jdk.rpm'
default['jdk']['s3_url'] = 'https://s3-us-west-2.amazonaws.com/aruns3/jre-8u73-linux-i586.rpm'
